name: Run AutoDelete_LR_120-1825 Every 6 Hours

on:
  schedule:
    - cron: "0 */1 * * *"  # Runs every 1 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Change this if needed

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: python Auto_delete_LR_120-1825/pyarmor_runtime_000000/___init___.py
